#!/bin/bash

npm un -S @axe-core/react @papillonbits/components @papillonbits/library @papillonbits/setup @primer/primitives @primer/view-components classnames clean-webpack-plugin copy-webpack-plugin css-minimizer-webpack-plugin dotenv-webpack html-webpack-plugin mini-css-extract-plugin prop-types react react-dom react-redux react-router react-router-dom redux redux-logger redux-mock-store redux-thunk uuid whatwg-fetch

npm un -D @babel/cli @babel/core @babel/eslint-parser @babel/plugin-transform-react-jsx @babel/plugin-transform-runtime @babel/preset-env @babel/preset-react @babel/register @babel/runtime @chromatic-com/storybook @storybook/addon-a11y @storybook/addon-actions @storybook/addon-backgrounds @storybook/addon-controls @storybook/addon-docs @storybook/addon-essentials @storybook/addon-highlight @storybook/addon-interactions @storybook/addon-jest @storybook/addon-links @storybook/addon-measure @storybook/addon-outline @storybook/addon-storyshots @storybook/addon-storyshots-puppeteer @storybook/addon-storysource @storybook/addon-styling-webpack @storybook/addon-themes @storybook/addon-toolbars @storybook/addon-viewport @storybook/manager-api @storybook/preview-api @storybook/react @storybook/react-webpack5 @storybook/source-loader @storybook/theming @svgr/webpack @testing-library/react autoprefixer babel-core babel-jest babel-loader babel-plugin-css-modules-transform babel-plugin-syntax-async-functions babel-plugin-transform-assets css-loader dotenv-cli eslint eslint-config-airbnb eslint-config-prettier eslint-import-resolver-alias eslint-plugin-import eslint-plugin-jest eslint-plugin-jsx-a11y eslint-plugin-prettier eslint-plugin-react eslint-plugin-react-hooks gh-pages husky identity-obj-proxy jest jest-axe jsdom jsdom-global lerna lint-staged npm-run-all postcss postcss-loader postcss-nested postcss-preset-env postcss-scss prettier regenerator-runtime sass sass-loader storybook storybook-addon-root-attributes style-loader stylelint stylelint-config-standard stylelint-order stylelint-prettier stylelint-scss webpack webpack-bundle-analyzer webpack-manifest-plugin webpack-merge

npm i -S @axe-core/react @papillonbits/components @papillonbits/library @papillonbits/setup @primer/primitives @primer/view-components classnames clean-webpack-plugin copy-webpack-plugin css-minimizer-webpack-plugin dotenv-webpack html-webpack-plugin mini-css-extract-plugin prop-types react react-dom react-redux react-router react-router-dom redux redux-logger redux-mock-store redux-thunk uuid whatwg-fetch

npm i -D @babel/cli @babel/core @babel/eslint-parser @babel/plugin-transform-react-jsx @babel/plugin-transform-runtime @babel/preset-env @babel/preset-react @babel/register @babel/runtime @chromatic-com/storybook @storybook/addon-a11y @storybook/addon-actions @storybook/addon-backgrounds @storybook/addon-controls @storybook/addon-docs @storybook/addon-essentials @storybook/addon-highlight @storybook/addon-interactions @storybook/addon-jest @storybook/addon-links @storybook/addon-measure @storybook/addon-outline @storybook/addon-storyshots @storybook/addon-storyshots-puppeteer @storybook/addon-storysource @storybook/addon-styling-webpack @storybook/addon-themes @storybook/addon-toolbars @storybook/addon-viewport @storybook/manager-api @storybook/preview-api @storybook/react @storybook/react-webpack5 @storybook/source-loader @storybook/theming @svgr/webpack @testing-library/react autoprefixer babel-core@^7.0.0-bridge.0 babel-jest babel-loader babel-plugin-css-modules-transform babel-plugin-syntax-async-functions babel-plugin-transform-assets css-loader dotenv-cli eslint eslint-config-airbnb eslint-config-prettier eslint-import-resolver-alias eslint-plugin-import eslint-plugin-jest eslint-plugin-jsx-a11y eslint-plugin-prettier eslint-plugin-react eslint-plugin-react-hooks@^4.6.2 gh-pages husky identity-obj-proxy jest jest-axe jsdom jsdom-global lerna lint-staged npm-run-all postcss postcss-loader postcss-nested postcss-preset-env postcss-scss prettier regenerator-runtime sass sass-loader storybook storybook-addon-root-attributes style-loader stylelint stylelint-config-standard stylelint-order stylelint-prettier stylelint-scss webpack webpack-bundle-analyzer webpack-manifest-plugin webpack-merge

npm run clean-up && npm run install-packages && npm run bootstrap-release
