export { getBabelLoaderAdvancedSetup } from './loader/babelLoader.js'
export { getCSSLoaderStandardSetup } from './loader/cssLoader.js'
export { getFontLoaderStandardSetup } from './loader/fontLoader.js'
export { getImageLoaderStandardSetup } from './loader/imageLoader.js'
export { getMarkdownLoaderStandardSetup } from './loader/markdownLoader.js'
export { getPostCSSLoaderStandardSetup } from './loader/postCSSLoader.js'
export { getSassLoaderStandardSetup } from './loader/sassLoader.js'
export { getSVGRLoaderStandardSetup, getSVGRLoaderAdvancedSetup } from './loader/svgrLoader.js'
export { getBannerPluginStandardSetup } from './plugin/bannerPlugin.js'
export { getCleanWebpackPluginStandardSetup, getCleanWebpackPluginAdvancedSetup } from './plugin/cleanWebpackPlugin.js'
export { getCopyWebpackPluginStandardSetup } from './plugin/copyWebpackPlugin.js'
export { getCSSMinimizerWebpackPluginStandardSetup } from './plugin/cssMinimizerWebpackPlugin.js'
export { getDotenvWebpackStandardSetup, getDotenvWebpackAdvancedSetup } from './plugin/dotenvWebpack.js'
export { getHotModuleReplacementPluginStandardSetup } from './plugin/hotModuleReplacementPlugin.js'
export { getHtmlWebpackPluginStandardSetup, getHtmlWebpackPluginAdvancedSetup } from './plugin/htmlWebpackPlugin.js'
export {
  MiniCSSExtractPluginLoader,
  getMiniCSSExtractPluginStandardSetup,
  getMiniCSSExtractPluginAdvancedSetup,
} from './plugin/miniCSSExtractPlugin.js'
export { getModuleConcatenationPluginStandardSetup } from './plugin/moduleConcatenationPlugin.js'
export { getWebpackBundleAnalyzerStandardSetup } from './plugin/webpackBundleAnalyzer.js'
export { getWebpackManifestPluginStandardSetup } from './plugin/webpackManifestPlugin.js'
export { getDevServerStandardSetup } from './server/devServer.js'
export { getWebpackCommonSetup } from './setup/commonSetup.js'
export { getWebpackDevelopmentSetup } from './setup/developmentSetup.js'
export { getWebpackProductionSetup } from './setup/productionSetup.js'
